[Writable]
  LogLevel = "DEBUG"
  [Writable.Device]
    DataTransform = true
    MaxCmdOps = 128

[Service]
  Port = 59999
  RequestTimeout = "5s"
  StartupMsg = "Example bitfields device service started"
  HealthCheckInterval = "10s"

[Clients]
  [Clients.core-data]
    Host = "localhost"
    Port = 59880

  [Clients.core-metadata]
    Host = "localhost"
    Port = 59881

[Device]
  Labels = [ "Bitfields" ]
  ProfilesDir = "res/profiles"
  DevicesDir = "res/devices"
