[Writable]
  LogLevel = 'DEBUG'
  [Device]
    DataTransform = true
    MaxCmdOps = 128
    MaxCmdResultLen = 256
    [Device.Discovery]
      Enabled = true
      Interval = 10

[Service]
  Port = 49999
  Timeout = 5000
  ConnectRetries = 10
  Labels = [ 'Template' ]
  StartupMsg = 'Template device started'
  CheckInterval = '10s'

[Clients]
  [Clients.edgex-core-data]
    Host = 'localhost'
    Port = 48080

  [Clients.edgex-core-metadata]
    Host = 'localhost'
    Port = 48081

[Driver]
  TestParam1 = 'Hello'
  TestParam2 = 'World'

