Writable:
  LogLevel: DEBUG
  Device:
    Discovery:
      Enabled: true
      Interval: 10

Service:
  Port: 59999
  StartupMsg: Example device service with discovery started
  HealthCheckInterval: 10s
  
# uncomment when running from command-line in hybrid mode without Config Provider
#Clients:
#  core-metadata:
#    Host: localhost
#    Port: 59881

Device:
  ProfilesDir: ./res/profiles
  DevicesDir: ./res/devices

MessageBus:
  Optional:
    ClientId: device-discovery
