Writable:
  LogLevel: DEBUG
  Driver:
    TestParam2: World
    TestParam3: Goodbye

Service:
  Host: "localhost"
  Port: 59999
  StartupMsg: Template device started
  HealthCheckInterval: 10s
  
# uncomment when running from command-line in hybrid mode without Config Provider
#Clients:
#  core-metadata:
#    Host: localhost
#    Port: 59881

Driver:
  TestParam1: "Hello"

Device:
  Labels: [ "Template" ]
  ProfilesDir: "./res/profiles"
  DevicesDir: "./res/devices"

MessageBus:
  Optional:
    ClientId: device-template
