[Service]
  Port = 49990
  Timeout = 5000
  ConnectRetries = 3
  Labels = [ "Counter" ]
  StartupMsg = "Example counting device started"
  CheckInterval = "10s"

[Clients]
  [Clients.Data]
    Host = "localhost"
    Port = 48080

  [Clients.Metadata]
    Host = "localhost"
    Port = 48081

[Device]
  DataTransform = false
  Discovery = false
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdResultLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = ""
  SendReadingsOnChanged = true

[Logging]
  RemoteURL = ""
  File = "-"
  LogLevel = "DEBUG"

[[DeviceList]]
  Name = "Counter1"
  Profile = "Example-Counter"
  Description = "An Example Counting Device"
  [DeviceList.Protocols]
    [DeviceList.Protocols.Counter]
      Index = "3"
  [[DeviceList.AutoEvents]]
    Resource = "Counter"
    OnChange = false
    Frequency = "10s"

[[DeviceList]]
  Name = "Counter2"
  Profile = "Example-Counter"
  Description = "Another Example Counting Device"
  [DeviceList.Protocols]
    [DeviceList.Protocols.Counter]
      Index = "58"
