[Writable]
  LogLevel = "DEBUG"

[Clients]
  [Clients.core-data]
    Host = "localhost"
    Port = 59880

  [Clients.core-metadata]
    Host = "localhost"
    Port = 59881

[Device]
  ProfilesDir = "res/profiles"
  DevicesDir = "res/devices"
