[Writable]
  LogLevel = 'DEBUG'

[Clients]
  [Clients.edgex-core-data]
    Host = 'localhost'
    Port = 48080

  [Clients.edgex-core-metadata]
    Host = 'localhost'
    Port = 48081

[[DeviceList]]
  Name = 'File1'
  Profile = 'FileProfile'
  Description = 'An Example File Device'
  [DeviceList.Protocols]
    [DeviceList.Protocols.Filename]
      Name = './res/lorem.txt'
